---
# roles/common/tasks/main.yml
- name: Disable firewall
  service: name=firewalld state=stopped enabled=false
  become: true

- name: Install python-pip
  yum: name=python-pip
  become: true

- name: Disable selinux
  copy: src=config dest=/etc/selinux/config
  become: true
  notify:
    - set permissive mode

- name: Install docker-py
  pip: name=docker-py version=1.5.0
  become: true

# seems to be a conflict with this and device-mapper. Just showed up 12/15 so it might be bug with a recent yum repo update?
- name: Remove lvm2
  yum: name=lvm2 state=absent
  become: true

- name: Install docker
  yum: name=docker
  become: true

- name: Setup docker
  template: src=docker.j2 dest='/etc/sysconfig/docker'
  become: true

- name: docker service
  service: name=docker state=started enabled=true
  become: true
