---
# roles/common/tasks/main.yml
#- name: Disable firewall
#  tags: common
#  service: name=firewalld state=stopped enabled=false
#  become: true

- name: Install python-pip
  tags: common
  yum: name=python-pip
  become: true

#- name: Disable selinux
#  copy: src=config dest=/etc/selinux/config
#  become: true
#  notify:
#    - set permissive mode

- name: Install docker-py
  tags: common
  pip: name=docker-py version=1.5.0
  become: true

- name: Install rsync
  tags: common
  yum: name=rsync
  become: true

# seems to be a conflict with this and device-mapper. Just showed up 12/15 so it might be bug with a recent yum repo update?
- name: Update lvm2
  tags: common
  yum: name=lvm2 state=latest
  become: true

# seems to be a conflict with this and device-mapper. Just showed up 12/15 so it might be bug with a recent yum repo update?
- name: Update lvm2
  tags: common
  yum: name=lvm2 state=latest
  become: true

- name: Install docker
  yum: name=docker
  become: true
  when: btrfs

- name: Setup docker
  template: src=docker.j2 dest='/etc/sysconfig/docker'
  become: true
  when: btrfs

- name: Setup docker filestore
  lineinfile: dest=/etc/sysconfig/docker-storage regexp="^DOCKER_STORAGE_OPTIONS=$" line="DOCKER_STORAGE_OPTIONS=-s btrfs"
  become: true
  when: btrfs

- name: docker service
  service: name=docker state=started enabled=true
  become: true
