---
# build-scale/handlers/main.yml
- name: push scale
  command: sh -c 'docker tag -f scale:{{ scale_docker_version }} {{ docker_registry }}scale:{{ scale_docker_version }}; docker push {{ docker_registry }}scale:{{ scale_docker_version }}'
  become: true

- name: push scale-slave
  command: sh -c 'docker tag -f scale-slave:{{ scale_docker_version }} {{ docker_registry }}scale-slave:{{ scale_docker_version }}; docker push {{ docker_registry }}scale-slave:{{ scale_docker_version }}'
  become: true

- name: push scale-web
  command: sh -c 'docker tag -f scale-web:{{ scale_docker_version }} {{ docker_registry }}scale-web:{{ scale_docker_version }}; docker push {{ docker_registry }}scale-web:{{ scale_docker_version }}'
  become: true

- name: push scale-web-static
  command: sh -c 'docker tag -f scale-web-static:{{ scale_docker_version }} {{ docker_registry }}scale-web-static:{{ scale_docker_version }}; docker push {{ docker_registry }}scale-web-static:{{ scale_docker_version }}'
  become: true

